version: '2.2'

services:
  zookeeper:
    image: zookeeper:3.4
    ports:
      - 2182:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: wurstmeister/kafka:0.11.0.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
    links:
      - zookeeper

  spark:
    image: sequenceiq/spark:1.6.0
    container_name: spark
    command: -d
    ports:
      - 8088:8088
      - 8042:8042
      - 4040:4040
      - 9000:9000

