version: '3'
services:
  namenode:
    image: 'kiwenlau/hadoop:1.0'
    container_name: hadoop-master
    volumes:
      - ./startup.sh:/usr/bin/startup.sh:ro
    ports:
     - '50070:50070'
     - '8088:8088'
    command: startup.sh 1 master
    stop_signal: SIGKILL
  datanode1:
    image: 'kiwenlau/hadoop:1.0'
    container_name: hadoop-slave1
    volumes:
      - ./startup.sh:/usr/bin/startup.sh:ro
    command: startup.sh 1 slave
    stop_signal: SIGKILL
